### ISSUE TITLE
In-game update checker says 1.2.4 is newer then 1.3.0 Dev I

### ISSUE THREAD

**Issue by JadianRadiator** [KyleLin921021/EkiMod#4]
In-game update checker says 1.2.4 is newer then 1.3.0 Dev I,
and is telling me to update to 1.2.4 even though it's older.

**Comment by ChAoSUnItY** [comment]
No, you should ignore that message since 1.3.0  currently is a dev version, also, I highly suggest not to use dev version (In Curse Forge it shows beta or alpha) version to construct a modpack.
